run:
    tests: false
    timeout: 5m
linters:
    disable-all: true
    enable:
        - asciicheck
        - dupl
        - errorlint
        - errcheck
        - exhaustive
        - exportloopref
        - funlen
        - gocognit
        - goconst
        - gocritic
        - gocyclo
        - goerr113
        - goheader
        - goimports
        - gomnd
        - goprintffuncname
        - gosec
        - gosimple
        - govet
        - ineffassign
        - lll
        - misspell
        - nakedret
        - nestif
        - nolintlint
        - prealloc
        - rowserrcheck
        - sqlclosecheck
        - staticcheck
        - stylecheck
        - typecheck
        - unconvert
        - unparam
        - unused
        - wastedassign
        - whitespace
        - wsl
linters-settings:
    funlen:
        lines: 150
        statements: 80
